du lieu cong OR

In [ ]:
from sklearn import linear_model
from sklearn.linear_model import Perceptron
x= [[0,0],[0,1],[1,0],[1,1]]
t= [0,1,1,1]

model=Perceptron()
model.fit(x,t)
model.score(x,t)

1.0

In [ ]:
x1=[[0.5,0.5],[-0.5,-0.5],[10,2.3],[-1,-2]]
y=model.predict(x1)
model.score(x,y)

0.25

In [ ]:
x2 = [[0.5,0.5],[0.5,0],[0,0.5],[0.4,0]]
y1=model.predict(x2)
model.score(x,y1)
print(y1)

[1 0 0 0]


In [ ]:
from sklearn.linear_model import Perceptron

x=[[-0.5,-0.5],[-0.5,0.5],[0.3,0.5],[-0.1,1]]
t = [1,1,0,0]


model=Perceptron()
model.fit(x,t)
model.score(x,t)

1.0

In [ ]:
x1= [[0,0],[0,1],[1,0],[1,1]]
y1 = model.predict(x)
model.score(x,y1)
print(y1)

[1 1 0 0]


phan loai hoa lan

In [ ]:
from sklearn.linear_model import Perceptron
from sklearn import datasets
from sklearn.model_selection import train_test_split 
# khong su dung du lieu train de test => overfix
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import StandardScaler # du lieu khong deu bat buoc scale de tra ve du lieu 0-1 de thuc hien sau do scale tra ve gia tri bd


iris = datasets.load_iris()
x= iris.data
y = iris.target
print(x[:5])
print(y[:5])

x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.3)
sc=StandardScaler()
sc.fit(x_train)
x_train_std=sc.transform(x_train)
x_test_std=sc.transform(x_test)
print(x_train_std[:5],x_train[:5])
print(y[:5])

model = Perceptron(max_iter=1000,eta0=0.4,random_state=0)
#max_iter : so lan hoc
#eta0 toc do hoc
model.fit(x_train_std,y_train)
y_pred=model.predict(x_test_std)

print(y_pred)
print(y_test)
print("Do chinh xac mo hinh:",accuracy_score(y_test,y_pred))

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]
[0 0 0 0 0]
[[-0.17149859 -0.30835229  0.27114791  0.18158251]
 [-0.17149859 -0.09250569  0.27114791  0.04539563]
 [ 0.18158674 -1.81927852  0.72306109  0.45395628]
 [-1.81923009 -0.09250569 -1.48001567 -1.45266011]
 [ 0.65236717 -0.30835229  0.32763706  0.18158251]] [[5.7 2.9 4.2 1.3]
 [5.7 3.  4.2 1.2]
 [6.  2.2 5.  1.5]
 [4.3 3.  1.1 0.1]
 [6.4 2.9 4.3 1.3]]
[0 0 0 0 0]
[1 2 2 0 2 2 0 0 1 0 0 2 2 1 2 0 0 1 1 2 0 1 2 1 2 1 1 0 1 2 2 0 1 2 2 2 1
 2 2 2 0 0 0 0 0]
[1 2 2 0 2 2 0 0 1 0 0 2 2 1 2 0 0 1 1 2 0 1 1 1 2 1 2 0 1 1 2 0 1 2 2 2 1
 2 2 2 0 0 0 0 1]
Do chinh xac mo hinh: 0.9111111111111111


In [ ]:

# Crabs 
import pandas as pd 
import matplotlib.pyplot as plt
import numpy as np
url = '/content/crabs.csv'
DataFrame = pd.read_csv(url)

print(DataFrame)



    speies sex  index  fontallip  rearwidth  length  width  depth
0        B   M      1        8.1        6.7    16.1   19.0    7.0
1        B   M      2        8.8        7.7    18.1   20.8    7.4
2        B   M      3        9.2        7.8    19.0   22.4    7.7
3        B   M      4        9.6        7.9    20.1   23.1    8.2
4        B   M      5        9.8        8.0    20.3   23.0    8.2
..     ...  ..    ...        ...        ...     ...    ...    ...
195      O   F     46       21.4       18.0    41.2   46.2   18.7
196      O   F     47       21.7       17.1    41.7   47.2   19.6
197      O   F     48       21.9       17.2    42.6   47.4   19.5
198      O   F     49       22.5       17.2    43.0   48.7   19.8
199      O   F     50       23.1       20.2    46.2   52.5   21.1

[200 rows x 8 columns]


In [ ]:
# thay the gia tri 
DataFrame['speies'].replace({"B":"0","O":"1"},inplace=True)
DataFrame['sex'].replace({"F":"0","M":"1"},inplace=True)
print(DataFrame)


    speies sex  index  fontallip  rearwidth  length  width  depth
0        0   1      1        8.1        6.7    16.1   19.0    7.0
1        0   1      2        8.8        7.7    18.1   20.8    7.4
2        0   1      3        9.2        7.8    19.0   22.4    7.7
3        0   1      4        9.6        7.9    20.1   23.1    8.2
4        0   1      5        9.8        8.0    20.3   23.0    8.2
..     ...  ..    ...        ...        ...     ...    ...    ...
195      1   0     46       21.4       18.0    41.2   46.2   18.7
196      1   0     47       21.7       17.1    41.7   47.2   19.6
197      1   0     48       21.9       17.2    42.6   47.4   19.5
198      1   0     49       22.5       17.2    43.0   48.7   19.8
199      1   0     50       23.1       20.2    46.2   52.5   21.1

[200 rows x 8 columns]


In [ ]:
DataFrame= datasets.load_iris()
x= DataFrame.data
y = DataFrame.target
print(x[:5])
print(y[:5])

x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.3)
sc=StandardScaler()
sc.fit(x_train)
x_train_std=sc.transform(x_train)
x_test_std=sc.transform(x_test)
print(x_train_std[:5],x_train[:5])
print(y[:5])

model = Perceptron(max_iter=1000,eta0=0.4,random_state=0)
#max_iter : so lan hoc
#eta0 toc do hoc
model.fit(x_train_std,y_train)
y_pred=model.predict(x_test_std)

print(y_pred)
print(y_test)
print("Do chinh xac mo hinh:",accuracy_score(y_test,y_pred))

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]
[0 0 0 0 0]
[[-0.93503021  1.80282885 -1.25733032 -1.33861195]
 [-0.2157762  -0.16389353  0.19589228 -0.06432134]
 [ 0.98298048 -1.39309502  1.0901831   0.70025303]
 [ 1.34260748  0.32778706  0.47535816  0.19053679]
 [ 0.62335347 -0.90141443  0.81071722  0.82768209]] [[5.1 3.8 1.6 0.2]
 [5.7 3.  4.2 1.2]
 [6.7 2.5 5.8 1.8]
 [7.  3.2 4.7 1.4]
 [6.4 2.7 5.3 1.9]]
[0 0 0 0 0]
[0 0 1 0 1 1 0 1 0 1 2 1 2 1 1 2 0 1 1 1 0 2 1 1 0 0 1 0 0 2 1 1 1 1 1 0 0
 1 0 2 1 1 2 0 1]
[0 0 2 0 1 1 0 1 0 2 2 1 2 1 1 2 0 1 1 1 0 2 1 1 0 0 1 0 0 2 1 1 1 1 1 0 0
 1 0 2 1 1 2 0 1]
Do chinh xac mo hinh: 0.9555555555555556
